reactphp/stream

composer.json, src/Stream.php, tests/StreamIntegrationTest.php, tests/StreamTest.php
=> Set read buffer to 0

.travis.yml, src/Stream.php
PR #20 introduced changes to the buffering behavior which is necessary for some event loops, however this turned out to be incompatible with HHVM.
=> HHVM does not support, nor require, unbuffered read operations

.travis.yml, composer.json, src/Buffer.php, src/Stream.php, tests/StreamIntegrationTest.php
Because *why not*… :-)
Now more seriously: This project is a low level lib that is used as a building block for quite a few higher level abstractions on top of it. As such, compatibility (even with significantly outdated versions) is a major concern to me.
Note that I'm not suggesting putting *significant amount* of work into this. The patch is already here and, personally, I see little harm in supporting this.
Also note that I'm not suggesting we need to keep support indefinitely. Should this ever turn out to be a burden in the future, e.g. because we actually *require* any new language features or some external lib, then I'm all for dropping support again.
=> [RFC] Improve compatibility with legacy versions

src/Buffer.php, tests/BufferTest.php
When `write()` is called in the event handler of a `drain` event, `Buffer` can write things twice.
Example:
``` php
$buffer = new Buffer();
$buffer->once('drain', function ($buffer) {
$buffer->write("bar\n");
});
$buffer->write("foo\n");
```
This write `"foo\nfoo\nbar\n"` instead of just `"foo\nbar\n"`.
This doesn't happen if `$buffer->write("bar\n");` is called on the next tick (which explains why it usually works).
This happens in actual code, e.g. when using `Util::pipe()` on a Readable which immediately emits a `'data'` event when `resume()` is called.
This PR fixes this by updating the internal buffer before emitting the `drain` event.
=> Fixed double-writes when write() is called during 'drain' event

src/BufferedSink.php, tests/BufferedSinkTest.php
This PR removes triggering progress notifications on the promise returned by BufferedSink.
I always recommend to avoid the progression API of promises (it's underspecified, has subtle problems and has little to do with promises). 
If you need to listen on data events, use the ReadableStream directly.
=> BufferedSink: Remove progress notifications

src/Buffer.php, tests/BufferTest.php
Hi.
I have Ratchet working 24/7 and sometimes it starting to use 100% of CPU. In this case I need to restart it and this helps. But it happend very often, so I debug it and found that `foef($this->stream)` do not return `true` when client disconnects while event loop tick is not ended. 
Same with `is_resource($this->stream)` it returns `true`.
I'm using:
- PHP 5.5.13 / Win8 x64
- PHP 5.4.10 / Win7 x64
- react/event-loop 0.4.1
- react/socket 0.4.2
- react/stream 0.4.2
- cboden/ratchet 0.3.3
In this case after
```php
$sent = fwrite($this->stream, $this->data);
```
`$this->lastError['message']` contains an error:
There is no way to catch such behavior using best practices, so I decide to check `$this->lastError['message']` on 'errno=10054'.
Maybe it will be more efficient if we will check …
=> Prevent infinite loop on connection close

composer.json, src/Stream.php, tests/StreamTest.php
Make sure any read error is handled just like write errors and results in an `error` event followed by closing the stream instance.
```
fread(): SSL: Connection reset by peer
fread(): {x} is not a valid stream resource
```
Fixes #18.
=> Emit error and close when reading from stream fails

src/BufferedSink.php, tests/BufferedSinkTest.php
Reverts reactphp/stream#24, because it currently blocks a v0.4.4 release. In other words: This restores the behavior present in the last v0.4.3 release.
I think we all agree that we want to remove the progress notifications, however this includes a BC break and thus should target a future v0.5.0 milestone.
=> Revert "BufferedSink: Remove progress notifications"

.travis.yml, examples/benchmark-throughput.php
Add benchmarking script to measure throughput in CI. This gives some interesting insights into differences between PHP versions / HHVM.
Also, this serves as the basis for future performance improvements.
=> Add benchmarking script to measure throughput in CI

src/Buffer.php, tests/BufferTest.php
Empty writes should not wait for writable event from the event loop and then literally try to do *nothing*.
Without this change, it would otherwise wait for the Buffer to return from a superfluous `fwrite($resource, '')` call.
=> Ignore empty writes to Buffer

src/Buffer.php, tests/BufferTest.php, tests/StreamIntegrationTest.php
Only report errors if *nothing* could be sent.
Any hard (permanent) error will fail to send any data at all.
Sending excessive amounts of data will only flush *some* data and then
report a temporary error (EAGAIN) which we do not raise here in order
to keep the stream open for further tries to write.
Should this turn out to be a permanent error later, it will eventually
send *nothing* and we can detect this.
This fixes a (very sublte) regression introduced via #25.
This also adds a bunch of unit tests so we hopefully no longer rely on any external test cases. The Buffer now has 100% code coverage in our tests.
I've intentionally kept this changeset to a minimum in order to ease review. I'll file a second PR to streamline the error handling system after this PR is in.
Also note that this …
=> Only emit permanent errors and otherwise keep retrying

src/Stream.php, tests/StreamTest.php
This has no effect by default and can be triggered by setting `bufferSize` to `null`.
This can result in huge performance improvements without causing any memory issues if the buffer size is limited by the underlying OS anyway (such as when reading from a TCP/IP socket).
Also, this can be used to avoid some SSL/TLS hackery in our socket-client component: https://github.com/reactphp/socket-client/blob/f905ec2a576b1242b10d5c1dbd2f0eb4fcea7f0c/src/SecureStream.php#L44
=> Support setting buffer size to null (infinite)

src/Buffer.php, src/Stream.php
The readable and writable side now use the same buffer sizes in order to avoid pausing the readable side when piping to a writable stream.
Running the `examples/benchmark-throughput.php` script, this change alone increases performance from ~100 MiB/s to ~1400 MiB/s on my (rather mediocre) test system, using PHP 7.0.8.
A buffer size of 64 KiB is a reasonable compromise between memory usage and performance, and the total buffer sizes can still be neglected even with thousands of open streams.
=> Increase performance by raising default buffer sizes to 64 KiB

src/Buffer.php, tests/BufferTest.php
The `Buffer` can be closed during the `drain` event, do not emit any further events in this case.
This is a very subtle bug and unlikely to ever have caused any real issues, but let's fix this for consistency.
Also, while we're at this, let's avoid some unnecessary function calls and improve performance a bit :)
Do not expect any major performance improvements here.
Running the examples/benchmark-throughput.php script, this change alone increases performance from ~100 MiB/s to ~110 MiB/s on my (rather mediocre) test system, using PHP 7.0.8.
Combined with #53 and #54, it increases performance from ~100 MiB/s to ~1950 MiB/s.
If you want to review, consider looking at the individual commits, this should make the changes pretty obvious.
=> Do not emit full-drain event if Buffer is closed during drain event

src/Buffer.php, tests/BufferTest.php
This only cleans up some of the internals and avoids some unnecessary function calls.
Running the examples/benchmark-throughput.php script, this change alone increases performance from ~100 MiB/s to ~120 MiB/s on my (rather mediocre) test system, using PHP 7.0.8.
Combined with #53, #54 and #55, it increases performance from ~100 MiB/s to ~2000 MiB/s.
If you want to review, consider looking at the individual commits, this should make the changes pretty obvious.
~~Marking this as WIP because this will need to be rebased once #52 is in.~~ Edit: done.
=> Simplify and improve error handling

src/Buffer.php, tests/BufferTest.php
The `Buffer` now behaves consistently when calling its `close()` method and follows the `close` event semantics.
This is kind of a rare edge case that can not be observed in normal operation, so most people won't be affected by this bug, nor does this cause a BC break.
The `Buffer` can be accessed via `Stream::getBuffer()` or it can be created directly, in which case these errors would have shown up.
=> Consistent close behavior for Buffer

src/Stream.php, tests/StreamTest.php
The `Buffer` can now be injected into the `Stream` (or be used standalone). This only adds an additional parameter and otherwise preserves BC.
~~Note that this builds on top of #61, so only the last commits are part of this PR.~~ Edit: rebased now that #61 is in.
=> The Buffer can now be injected into the Stream (or be used standalone)

tests/StreamTest.php
This PR makes `React\Stream\Stream` 100% covered with unit tests.
=> Improves test coverage

src/Buffer.php, tests/BufferTest.php, tests/UtilTest.php
Remove the `full-drain` event from the `Buffer` and instead close as appropriate internally. This event is currently only used to `end()` the buffer. This does not change any of the outside behavior otherwise.
While not used anywhere in React's ecosystem, this is still a BC break because others may actually rely on this event. However, this event has never been documented anyway, so chances are nobody will be affected by this BC break.
=> Remove custom full-drain event

src/Buffer.php, tests/BufferTest.php
Fixes a major issue introduced via #63 earlier today.
=> Fix removing resource from loop after buffer is completely drained

README.md, src/Buffer.php, src/ReadableStream.php, src/ReadableStreamInterface.php, src/Stream.php, src/ThroughStream.php, src/WritableStream.php, src/WritableStreamInterface.php, tests/BufferTest.php, tests/StreamIntegrationTest.php, tests/StreamTest.php
This simple PR changes it so that we only emit event arguments that are actually part of the event, i.e. we no longer emit the instance this event was emitted on. This was actually an undocumented feature, so some component may have relied on this.
Among others, this fixes several issues because these instance where never emitted consistently in the first place. In particular, the `forwardEvents` helper is used throughout React's ecosystem and has never actually updated the instances, as it has never checked any of the event arguments.
I've updated the documentation to now explicitly state which arguments are actually passed to the event handlers.
Not passing these unneeded instances also helps with improving performance slightly. On my system, the benchmark examples went from ~1980 MiB/s …
=> Consistent event arguments and documentation

README.md, src/BufferedSink.php, src/ReadableStream.php, src/Stream.php, src/ThroughStream.php, src/WritableStream.php, tests/ReadableStreamTest.php, tests/StreamTest.php, tests/ThroughStreamTest.php, tests/WritableStreamTest.php
An `end` event will (only) be emitted when the stream/connection reached EOF (end of file or other side closes the connection)
This is potentially a BC break for anybody who relied on the existing inconsistent(!) behavior, where the `end` was usually(!) emitted right before a `close` event. Consumers should use the unchanged `close` event in this case.
Closes #59
=> Consistent end event semantics (EOF)

README.md, src/CompositeStream.php, src/ReadableStream.php, src/ReadableStreamInterface.php, src/Stream.php, src/Util.php, tests/CompositeStreamTest.php, tests/ReadableStreamTest.php, tests/StreamTest.php, tests/ThroughStreamTest.php, tests/UtilTest.php
The `pipe()` method previously showed some inconsistent behavior depending on which side of the pipe closed at which time (prior to piping or during piping).
The `pipe()` method now shows consistent behavior of calling `pause()` on the source side if the target is saturated or closed and now cleanly removes the event forwarding if either side is closed.
This should not affect normal usage, but some of the more hidden scenarios may in fact rely on the previous behavior. As such, I'm marking this as a BC break just to be safe.
If you want to review, also consider looking at the individual commits, this should make the changes more obvious.
Fixes / closes #36
Builds on top of #70
=> Consistent pipe() semantics for closed and closing streams

README.md, src/Buffer.php, src/BufferedSink.php, src/ReadableStreamInterface.php, src/ThroughStream.php, src/WritableStream.php, src/WritableStreamInterface.php
Et voilà, consistent method semantics and documentation :tada:
This pretty much only adds consistent documentation for what is currently undocumented and implicitly assumed.
This should in fact not break any of the existing assumptions and as such should not be considered a BC break. Given that this current behavior was mostly underdocumented or undocumented, I'll mark this as a BC break just to be safe in case any implementation relies on undocumented features which might now be prohibited.
=> Consistent method semantics and documentation

src/Stream.php, src/ThroughStream.php, tests/BufferedSinkTest.php, tests/CompositeStreamTest.php, tests/StreamTest.php, tests/ThroughStreamTest.php
Builds on top of #72 and #73 and makes sure all methods obey strict method and event semantics for some of the less obvious cases. This project now has 100% test coverage :tada:
=> Obey strict method and event semantics for closed and piped streams

README.md, src/DuplexStreamInterface.php, src/ReadableStreamInterface.php, src/WritableStreamInterface.php
Et voilà, consistent event semantics and documentation :tada:
This pretty much only adds consistent documentation for what is currently undocumented and implicitly assumed.
This should in fact not break any of the existing assumptions and as such should not be considered a BC break. Given that this current behavior was mostly underdocumented or undocumented, I'll mark this as a BC break just to be safe in case any implementation relies on undocumented features which might now be prohibited.
Builds on top of #72.
=> Consistent event semantics and documentation

composer.json
```bash
$ composer validate
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
keywords.5 : invalid value (I/O), must match [\p{N}\p{L} ._-]+
```
=> Fix composer keyword (I/O -> io)

src/Buffer.php, src/Stream.php, tests/BufferTest.php, tests/EnforceBlockingWrapper.php, tests/StreamTest.php
Opening this an RFC, any input is welcome! :+1: 
Reading from a stream should _never_ block the loop.
This is known to be an issue for process pipes on Windows.
Refs: https://github.com/reactphp/child-process/issues/9 and https://github.com/reactphp/react/issues/68
=> Enforce using non-blocking I/O

examples/cat.php, src/Stream.php, tests/StreamIntegrationTest.php
Currently, reading from a pipe stream (such as STDIN) causes SEGFAULTs on legacy PHP < 5.4.
I've added a very simple `cat.php` example which highlights this issue.
This patch avoids switching to unbuffered mode for pipe streams on PHP < 5.4 and thus avoids this issue on all versions. Technically, unbuffered reads aren't really needed here for any PHP version, but not using unbuffered reads shows a 10%-20% performance penalty.
Fixes #78
=> Do not use unbuffered reads on pipe streams for legacy PHP < 5.4

README.md, examples/benchmark-throughput.php, examples/cat.php, src/ReadableResourceStream.php, tests/EnforceBlockingWrapper.php, tests/ReadableResourceStreamTest.php
=> Add ReadableResourceStream

README.md, examples/benchmark-throughput.php, examples/cat.php, src/ReadableResourceStream.php, src/Stream.php, src/WritableResourceStream.php, tests/ReadableResourceStreamTest.php, tests/StreamIntegrationTest.php, tests/UtilTest.php, tests/WritableStreamResourceTest.php
The old `Buffer` has been renamed to `WritableResourceStream` to complement the `ReadableResourceStream` introduced via #83.
Note that the `WritableResourceStream` now rejects read-only streams, so this may affect BC. If you want a read-only resource, use `ReadableResourceStream` instead of `Stream`.
Refs #37 and builds on top of #83.
=> Add WritableResourceStream

README.md, examples/benchmark-throughput.php, src/DuplexResourceStream.php, src/Stream.php, tests/DuplexResourceStreamIntegrationTest.php, tests/DuplexResourceStreamTest.php
The old `Stream` has been renamed to `DuplexResourceStream` to complement the `ReadableResourceStream` and `WritableResourceStream` introduced via #83 and #84.
Note that the `DuplexResourceStream` now rejects read-only or write-only streams, so this may affect BC. If you want a read-only or write-only resource, use `ReadableResourceStream` or `WritableResourceStream` instead of `DuplexResourceStream`.
Also marking this as a bug fix because the old behavior with regards to stream resource that were not opened in duplex mode could actually result in runtime errors.
The `Stream` class is one of the main classes in this package, so I've added a deprecated dummy `Stream` class that simply extends the new `DuplexResourceStream` for BC reasons only. This means that existing packages can keep …
=> Add DuplexResourceStream and deprecate Stream

README.md, src/CompositeStream.php, src/DuplexResourceStream.php, src/WritableStreamInterface.php, tests/CompositeStreamTest.php, tests/DuplexResourceStreamTest.php
The semantics for this are currently not explicit and the `DuplexResourceStream` (previously `Stream`) class has a very unclear `end()` logic implemented. It currently turns the stream into non-readable mode but keeps emitting readable events despite.
This PR ensures we use consistent semantics to ensure duplex streams SHOULD also end the readable side (unless this is a stream that supports half-open mode, see #27).
This should in fact not break any of the existing assumptions and as such should not be considered a BC break. Given that this current behavior was mostly underdocumented or undocumented, I'll mark this as a BC break just to be safe in case any implementation relies on undocumented features which might now be prohibited.
Builds on top of #72.
=> Consistent semantics for DuplexStreamInterface::end() to ensure it SHOULD also end readable side

src/ThroughStream.php, tests/ThroughStreamTest.php
It no longer builds on top of CompositeStream, which helps cleaning up
the class hierarchy and removes unneeed readable and writable objects.
This is technically a BC break because it changes the class hierarchy, but outside behavior is actually unchanged. Any of the known implementations (http://packanalyst.com/class?q=React%5CStream%5CThroughStream) would not be affected by this change.
=> ThroughStream is now a direct implementation of DuplexStreamInterface

README.md, src/ThroughStream.php, tests/ThroughStreamTest.php
Previously, one had to `extend` the `ThroughStream` in order to implement custom filtering behavior. However, there is no public implementation of this available: http://packanalyst.com/class?q=React%5CStream%5CThroughStream
With this PR applied, one can now simply pass a callback function to its constructor like this:
```php
$through = new ThroughStream(function ($data) {
return json_encode($data) . PHP_EOL;
});
$through->on('data', $this->expectCallableOnceWith("[2, true]\n"));
$through->write(array(2, true));
```
Builds on top of #88
=> Simplify ThroughStream by using data callback instead of inheritance

README.md, src/ReadableStreamInterface.php, src/WritableStreamInterface.php
The `error` event is currently allowed to be emitted for non-fatal errors, but our implementations actually only ever emit this as a fatal error and then close the stream.
This simple PR ensures that the `error` event is documented to only be allowed for fatal errors that will result in the stream being closed. Marking this as a new feature because one can now rely on this event and build reliable error handling logic.
This means that this will not affect normal usage. However, it is a BC break for those that currently implement our interfaces and currently emit non-fatal errors. Empirical evidence suggests that this is not common at all (no single use of this is known).
Builds on top of #73 
Resolves / closes #79
=> Only emit `error` event for fatal errors

README.md, examples/benchmark-throughput.php, src/DuplexResourceStream.php, src/ReadableResourceStream.php, src/WritableResourceStream.php, tests/WritableStreamResourceTest.php
Remove public $stream property from all resource streams. This property has attracted some low quality code and interacting with it could easily break the stream semantics.
Empirical evidence suggests this isn't really needed anyway, so I propose to remove it from the public API for now. Should we need this again in the future, it's a simple feature addition with no BC break, so I'd suggest removing this until we find a use case that actually relies on this.
=> Remove public $stream property from all resource streams

README.md, src/DuplexResourceStream.php, src/ReadableResourceStream.php, src/WritableResourceStream.php, tests/DuplexResourceStreamIntegrationTest.php, tests/DuplexResourceStreamTest.php, tests/ReadableResourceStreamTest.php, tests/WritableStreamResourceTest.php
Remove public $bufferSize property from DuplexResourceStream and ReadableResourceStream and public $softLimit property from WritableResourceStream. These properties have attracted some low quality code and interacting with it in the wrong way could easily break the streams.
Empirical evidence suggests this isn't really needed anyway, so I propose to remove it from the public API for now. Should we need this again in the future, it's a simple feature addition with no BC break, so I'd suggest removing this until we find a use case that actually relies on this.
Refs #90
=> Use constructor parameters instead of public buffer property

src/CompositeStream.php, tests/CompositeStreamTest.php
Remove inconsistent and unneeded forwarding of calls to `pause()` and `resume()` to the source stream for `CompositeStream`. This is actually entirely unneeded as the source stream will be paused automatically once it tries writing data to a paused stream anyway. This is now consistent with how literally all other streams work.
I do not consider this to be a bug fix, a new feature nor a BC break. This undocumented forwarding is plain unneeded. Prior to #88 this would also have affected the `ThroughStream`, so it makes sense to address this as part of the same release.
=> CompositeStream forwards pause to pipe source on first write attempt

composer.json
=> Actually require all dependencies so this is self-contained

src/CompositeStream.php, src/DuplexResourceStream.php, src/ReadableResourceStream.php, src/ThroughStream.php, src/Util.php, src/WritableResourceStream.php
Classes should be used via composition rather than extension.
This reduces our API footprint and avoids future BC breaks by avoiding
exposing its internal assumptions.
Builds on top of #95
=> Mark all classes as final

.travis.yml, README.md
Refs https://github.com/reactphp/dns/pull/56
=> Support legacy PHP 5.3 through PHP 7.1 and HHVM

README.md
Resolves / closes #34
Resolves / closes #81
=> Improve usage documentation

README.md, src/CompositeStream.php, tests/CompositeStreamTest.php
If either side of the composite stream closes, it will also close the other side.
This PR ensures that if either side is already closed during instantiation, it will also close the other side. Depending on how you view this, this is either a new feature or a bug fix.
=> CompositeStream starts closed if either side is already closed

.travis.yml
Ignore HHVM test failures for now until Travis tests work again.
=> Ignore HHVM test failures for now until Travis tests work again

README.md, src/WritableResourceStream.php, tests/FunctionalInternetTest.php
This complements the `$readChunkSize` that is available for the readable side of streams.
Among others, this can be used to work-around the TLS stream write issues for chunks larger than ~30KB mentioned in #64.
=> Add optional $writeChunkSize parameter for max number of bytes to write

src/WritableResourceStream.php, tests/WritableStreamResourceTest.php
Currently unlike `ReadableResourceStream` the `WritableResourceStream` doesn't automatically closes the underlying stream resource with `fclose`. This PR aims to add that, but as of creating this PR two tests fail, purposely not updated tests to discuss how to handle those here before fixing them.
=> Close the underlying stream when closing the stream

.travis.yml
Travis is in the process of upgrading the base distro (https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming) and despite all PRs currently being "green", will soon start to mark the current master as broken.
While updating the default distro, they also removed support for some older versions of PHP (travis-ci/travis-ci#7163). These versions are still supported by this project, so we now have to explicitly define the base distro to test against.
Builds on top of #106
Originally from https://github.com/clue/php-connection-manager-extra/pull/24
=> Lock Travis distro so new defaults will not break the build 

.travis.yml, tests/DuplexResourceStreamIntegrationTest.php
Squashed by @clue, originally from
https://github.com/reactphp/socket/pull/124
Resolves / closes #111
=> Test Mac OS X on Travis

src/CompositeStream.php, src/WritableResourceStream.php, tests/CompositeStreamTest.php
This simple PR ensures that pending event listeners are removed after closing the (rarely used) `CompositeStream` in order to simplify garbage collection.
Builds on top of #107 and #69
=>  Remove event listeners from CompositeStream once closed and remove remove undocumented left-over close event argument 

.travis.yml
Builds on top of #112
Refs #106
=> Ignore Mac OS X test failures for now until Travis tests work again

src/WritableResourceStream.php, tests/DuplexResourceStreamTest.php, tests/ReadableResourceStreamTest.php, tests/WritableStreamResourceTest.php
This fixes a minor issue where valid stream resources opened with valid flags such as `re` where not properly rejected.
Builds on top of #83, #84, #85
=> Igore excessive fopen() mode flags for WritableResourceStream

src/DuplexResourceStream.php, src/ReadableResourceStream.php, tests/DuplexResourceStreamTest.php, tests/ReadableResourceStreamTest.php
This ensures that the stream resources will only be added to and removed from the EventLoop if applicable. This ensures compatibility with the stricter definition of upcoming EventLoop releases and to prevent related issues. This is not an issue at the time of filing this PR. 
Refs https://github.com/reactphp/event-loop/pull/110 and https://github.com/reactphp/event-loop/pull/118
Builds on top of #94
=> Fix forward compatibility with upcoming EventLoop releases

composer.json, tests/DuplexResourceStreamTest.php, tests/ReadableResourceStreamTest.php, tests/TestCase.php, tests/WritableStreamResourceTest.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCase. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`^4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06) and [`^5.7`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#570---2016-12-02), that support this namespace.
=> Forward compatibility with PHPUnit 6

src/DuplexResourceStream.php, src/ReadableResourceStream.php
We've been able to track this back to legacy PHP bug https://bugs.php.net/bug.php?id=61019 which was fixed via https://github.com/php/php-src/commit/1ec83d44a1601c3560f430e08af9698bf8fb075c.
This patch avoids switching to unbuffered mode for pipe streams on PHP < 5.4.28 and PHP < 5.5.12 and thus avoids this issue on all versions. Technically, unbuffered reads aren't really needed here for any PHP version, but not using unbuffered reads shows a 10%-20% performance penalty.
Builds on top of #80
Refs https://github.com/reactphp/child-process/issues/40
=> Work around reading from unbuffered pipe stream in legacy PHP < 5.4.28 and PHP < 5.5.12

composer.json, tests/DuplexResourceStreamIntegrationTest.php
Refs https://github.com/reactphp/event-loop/pull/72 and https://github.com/reactphp/event-loop/pull/128
=> Fix test suite forward compatibility with upcoming EventLoop releases

tests/DuplexResourceStreamIntegrationTest.php, tests/DuplexResourceStreamTest.php, tests/ReadableResourceStreamTest.php, tests/WritableStreamResourceTest.php
This simple PR fixes a minor typo recently introduced via #128. Also, while I'm at it, this also includes some trivial adjustments to avoid risky tests (as of #122).
Builds on top of #128 and #122
=> Fix test suite when using legacy LibEventLoop and avoid risky tests

README.md, tests/FunctionalInternetTest.php
The test suite contains some tests that rely on a working internet connection and upload more than 30 MB(!) and does not apply any timeouts for this. This simple PR reduces this size to 50 KB (which exhibits the same behavior as documented in #105) and applies a timeout of 10s for each test. Additionally, we now document this in our README and give instructions on how these tests can be skipped.
Builds on top of #105
Refs https://github.com/reactphp/socket/pull/146
=> Add test group to skip integration tests relying on internet connection and apply timeouts

src/DuplexResourceStream.php, src/ReadableResourceStream.php, src/ThroughStream.php, src/Util.php, src/WritableResourceStream.php
The performance increase measuring using `examples/91-benchmark-throughput.php -t30` is as follows:
* `master`: 3.0GB/s
* This PR: 3.1GB/s
* Raw Linux using `cat /dev/zero | pv > /dev/null`: 3.2GB/s
=> Improve performance by prefixing all global functions calls with \ to skip the look up and resolve process and go straight to the global function

src/DuplexResourceStream.php, src/ReadableResourceStream.php, tests/DuplexResourceStreamIntegrationTest.php, tests/ReadableResourceStreamTest.php
While working on https://github.com/reactphp/event-loop/pull/112 I ran into an issue with suddenly closed streams. Traced the issue down to `''` coming from streams when using the `ext-uv` loop. Adding this check before closing the stream resolved the issue for `ext-uv`.
Todo: 
Relates to https://github.com/reactphp/event-loop/pull/112
=> Only close stream when the we reached end of the stream

.travis.yml, src/WritableResourceStream.php, tests/FunctionalInternetTest.php
This changeset fixes faulty write buffer error handling when sending larger data chunks over TLS (HTTPS) streams as exhibited on Mac OS X only. This component will now only report a write error when *nothing* could be sent *and* and error has been reported. This indicates a fatal error condition, whereas all other cases mean that a write should be retried according to how the loop reports the stream as writable.
Supersedes / closes #149, thanks @WyriHaximus and @mpociot for reporting and filing an initial work-around.
=> Fix faulty write buffer behavior when sending large data chunks over TLS (Mac OS X only)

README.md, composer.json, examples/01-http.php, examples/02-https.php, examples/11-cat.php, examples/91-benchmark-throughput.php, src/DuplexResourceStream.php, src/ReadableResourceStream.php, src/ReadableStreamInterface.php, src/WritableResourceStream.php, src/WritableStreamInterface.php, tests/DuplexResourceStreamTest.php, tests/ReadableResourceStreamTest.php, tests/WritableResourceStreamTest.php
This changeset simplifies usage by supporting the new [default loop](https://github.com/reactphp/event-loop#loop).
```php
// old (still supported)
$stream = new ReadableResourceStream($resource, $loop);
$stream = new WritabeResourceStream($resource, $loop);
$stream = new DuplexResourceStream($resource, $loop);
// new (using default loop)
$stream = new ReadableResourceStream($resource);
$stream = new WritabeResourceStream($resource);
$stream = new DuplexResourceStream($resource);
```
Builds on top of https://github.com/reactphp/event-loop/pull/226, https://github.com/reactphp/event-loop/pull/229 and https://github.com/reactphp/event-loop/pull/232
=> Simplify usage by supporting new default loop
